import pandas as pd

INPUT_PATH = "data/golden/golden_set.csv"
OUTPUT_PATH = "data/golden/golden_set.csv"

labels = {
    1: "software_update",
    2: "hardware_device",
    3: "battery_charging",
    4: "general_troubleshooting",
    5: "software_update",
    6: "billing_payment",
    7: "services_media",
    8: "connectivity",
    9: "general_troubleshooting",
    10: "app_issue",
    11: "hardware_device",
    12: "general_troubleshooting",
    13: "general_troubleshooting",
    14: "services_media",
    15: "order_purchase",
    16: "hardware_device",
    17: "services_media",
    18: "general_troubleshooting",
    19: "account_access",
    20: None,

    21: "order_purchase",
    22: "general_troubleshooting",
    23: "general_troubleshooting",
    24: "account_access",
    25: "hardware_device",
    26: "general_troubleshooting",
    27: "account_access",
    28: "general_troubleshooting",
    29: "order_purchase",
    30: "hardware_device",
    31: "software_update",
    32: "general_troubleshooting",
    33: "battery_charging",
    34: "general_troubleshooting",
    35: "hardware_device",
    36: "app_issue",
    37: "account_access",
    38: "services_media",
    39: "account_access",
    40: "hardware_device",

    41: "account_access",
    42: "software_update",
    43: "software_update",
    44: "battery_charging",
    45: "order_purchase",
    46: "general_troubleshooting",
    47: "battery_charging",
    48: "account_access",
    49: "general_troubleshooting",
    50: "account_access",
    51: "billing_payment",
    52: "hardware_device",
    53: "software_update",
    54: "software_update",
    55: "order_purchase",
    56: "hardware_device",
    57: "app_issue",
    58: "connectivity",
    59: "software_update",
    60: "services_media",

    61: "software_update",
    62: "connectivity",
    63: "general_troubleshooting",
    64: "general_troubleshooting",
    65: "battery_charging",
    66: "services_media",
    67: "app_issue",
    68: "general_troubleshooting",
    69: "account_access",
    70: "app_issue",
    71: "services_media",
    72: "services_media",
    73: "battery_charging",
    74: "software_update",
    75: "billing_payment",
    76: "order_purchase",
    77: "hardware_device",
    78: "services_media",
    79: "connectivity",
    80: "billing_payment",

    81: "general_troubleshooting",
    82: "account_access",
    83: "general_troubleshooting",
    84: "general_troubleshooting",
    85: "general_troubleshooting",
    86: "account_access",
    87: "general_troubleshooting",
    88: "general_troubleshooting",
    89: "general_troubleshooting",
    90: "hardware_device",
    91: "battery_charging",
    92: "services_media",
    93: "connectivity",
    94: "battery_charging",
    95: "software_update",
    96: "general_troubleshooting",
    97: "general_troubleshooting",
    98: "general_troubleshooting",
    99: "battery_charging",
    100: "services_media",

    101: "hardware_device",
    102: "battery_charging",
    103: "battery_charging",
    104: "general_troubleshooting",
    105: "connectivity",
    106: "connectivity",
    107: "software_update",
    108: "hardware_device",
    109: "general_troubleshooting",
    110: "battery_charging",
    111: "services_media",
    112: "general_troubleshooting",
    113: "general_troubleshooting",
    114: "general_troubleshooting",
    115: "services_media",
    116: "order_purchase",
    117: "order_purchase",
    118: "hardware_device",
    119: "app_issue",
    120: "general_troubleshooting",

    121: "software_update",
    122: "connectivity",
    123: "general_troubleshooting",
    124: "general_troubleshooting",
    125: "battery_charging",
    126: "battery_charging",
    127: "general_troubleshooting",
    128: "general_troubleshooting",
    129: "account_access",
    130: "battery_charging",
    131: "general_troubleshooting",
    132: "app_issue",
    133: "billing_payment",
    134: "software_update",
    135: "services_media",
    136: "services_media",
    137: "connectivity",
    138: "connectivity",
    139: "app_issue",
    140: "general_troubleshooting",

    141: "general_troubleshooting",
    142: "general_troubleshooting",
    143: "general_troubleshooting",
    144: "app_issue",
    145: "general_troubleshooting",
    146: "battery_charging",
    147: "hardware_device",
    148: "connectivity",
    149: "account_access",
    150: "account_access",
    151: "services_media",
    152: None,
    153: "services_media",
    154: "software_update",
    155: "general_troubleshooting",
    156: "hardware_device",
    157: "services_media",
    158: "services_media",
    159: "general_troubleshooting",
    160: "account_access",

    161: "general_troubleshooting",
    162: "general_troubleshooting",
    163: "general_troubleshooting",
    164: "general_troubleshooting",
    165: "connectivity",
    166: "app_issue",
    167: "connectivity",
    168: "app_issue",
    169: "general_troubleshooting",
    170: "general_troubleshooting",
    171: "general_troubleshooting",
    172: "general_troubleshooting",
    173: "connectivity",
    174: "hardware_device",
    175: "app_issue",
    176: "software_update",
    177: "account_access",
    178: "battery_charging",
    179: "account_access",
    180: "software_update",

    181: "software_update",
    182: "services_media",
    183: "software_update",
    184: "services_media",
    185: "general_troubleshooting",
    186: "connectivity",
    187: "connectivity",
    188: "services_media",
    189: "account_access",
    190: "hardware_device",
    191: "order_purchase",
    192: "general_troubleshooting",
    193: "battery_charging",
    194: "general_troubleshooting",
    195: "services_media",
    196: "connectivity",
    197: "general_troubleshooting",
    198: "billing_payment",
    199: "general_troubleshooting",
    200: "connectivity",
}

df = pd.read_csv(INPUT_PATH)

df["intent"] = df["golden_id"].map(labels)

# Remove examples explicitly marked for exclusion.
df = df[df["intent"].notna()].copy()

df.to_csv(OUTPUT_PATH, index=False)

print("=" * 70)
print("GOLDEN SET ANNOTATION SAVED")
print("=" * 70)

print(f"Final examples: {len(df)}")
print("\nIntent distribution:")
print(df["intent"].value_counts())

print("\nSaved to:", OUTPUT_PATH)